export const ar = {
    hi: "مرحبا",
    intro_main_text:"مرحبا! انا د.مي البنا دكتوره مختصه في تغذية صحة المرأه",
    home:"الرئيسية",
    about:"عن العياده",
    login:"تسجيل الدخول",
    complete_signup:"اكمال التسجيل",
    create_password:"انشاء كلمة السر",
    input_password:"ادخال كلمة السر",
    confirm:"تأكيد",
    first_name:"الاسم الاول",
    last_name:"اللقب",
    logout:"تسجيل الخروج",
    signup:"التسجيل",
    phone_number:"رقم الموبايل",
    "don't have an account?":"ليس لديك حساب؟",
    "already have an account?":"لديك حساب بالفعل؟",
    phone_not_registered:"هذا الرقم غير مسجل",
    failed:'خطأ',
    incorrect_password:"كلمة السر غير صحيحه",
    "My profile":"الصفحه الشخصيه",
    password:'كلمة السر',
    footer_description:'My mission is to help your balance your hormones after coming off birth control',
    'keep connected':'Keep connected',
    'follow us':'تابعنا علي',
    'call us':'اتصل بنا',
    'subscribe':'اشتراك',
    'footer_rights':' جميع الحقوق محفوظه ©',
    'Subscribe to our newsletter':'اشترك في خدمة البريد الالكتروني'


}