export const en ={
    hi: "Hi",
    intro_main_text:"Women have unique nutritional needs.",
    intro_description:"Work with Dr.Mai to learn about your nutrition needs as a woman for all stages of life & health conditions!",
    home:"Home",
    about:"About",
    login:"Login",
    complete_signup:"Complete Signup",
    create_password:"Create password",
    input_password:"Password",
    confirm:"Confirm",
    first_name:"First name",
    last_name:"Last name",
    logout:"logout",
    signup:"signup",
    phone_number:"phone number",
    "don't have an account?":"Don't have an account?",
    "already have an account?":"Already have an account?",
    phone_not_registered:"This number is not registered",
    failed:'Failed',
    incorrect_password:"The password is incorrect",
    "My profile":"My profile",
    we_can_help_with:"We can help with",
    'Planning for pregnancy':'Planning for pregnancy',
    'Pre and post natal nutrition':'Pre and post natal nutrition',
    'Nutrition through the lifecycle':'Nutrition through the lifecycle',
    'Nutrition for active lifecycle':'Nutrition for active lifecycle',
    'PCOS':'PCOS',
    password:'password',
    footer_description:'My mission is to help your balance your hormones after coming off birth control',
    'keep connected':'Keep connected',
    'follow us':'FOLLOW US',
    'call us':'CALL US',
    'subscribe':'subscribe',
    'footer_rights':'© Copyright 2023 nutrime・All rights reserved',
    'Subscribe to our newsletter':'Subscribe to our newsletter'
}